all: TCPClientRead TCPClientWrite TCPServer
TCPClientRead: TCPClientReader.c
	gcc TCPClientReader.c  -o TCPClientRead
TCPClientWrite: TCPClientWriter.c 
	gcc TCPClientWriter.c  -o TCPClientWrite
TCPServer: TCPServer.c 
	gcc TCPServer.c -o TCPServer
